"""Fixed Hinglish spellings, looked up before the transliteration rules run.

Keys are single Devanagari words exactly as Whisper writes them. Add an entry whenever a
word comes out with a spelling you do not like; several Devanagari spellings of the same
word may map to one Hinglish spelling.
"""

WORDS: dict[str, str] = {
    # --- everyday words ------------------------------------------------------
    "और": "aur", "है": "hai", "हैं": "hain", "में": "mein", "मैं": "main", "नहीं": "nahi",
    "हूं": "hoon", "हूँ": "hoon", "हो": "ho", "हों": "hon", "क्या": "kya", "कि": "ki", "की": "ki",
    "को": "ko", "से": "se", "पर": "par", "यह": "yeh", "ये": "ye", "वो": "wo", "वह": "woh",
    "हम": "hum", "हमें": "humein", "हमारा": "hamara", "हमारे": "hamare", "हमारी": "hamari",
    "आप": "aap", "आपको": "aapko", "आपका": "aapka", "आपके": "aapke", "आपकी": "aapki",
    "तो": "to", "भी": "bhi", "ही": "hi", "था": "tha", "थी": "thi", "थे": "the",
    "रहा": "raha", "रहे": "rahe", "रही": "rahi", "गया": "gaya", "गयी": "gayi", "गई": "gayi", "गए": "gaye",
    "लिए": "liye", "लिये": "liye", "चाहिए": "chahiye", "कोई": "koi", "कुछ": "kuch", "अभी": "abhi",
    "यहाँ": "yahan", "यहां": "yahan", "वहाँ": "wahan", "वहां": "wahan", "कहाँ": "kahan", "कहां": "kahan",
    "कैसे": "kaise", "कैसा": "kaisa", "कैसी": "kaisi", "कब": "kab", "क्यों": "kyun", "क्योंकि": "kyunki",
    "बहुत": "bahut", "ठीक": "theek", "अच्छा": "accha", "अच्छी": "acchi", "अच्छे": "acche",
    "साहब": "sahab", "साब": "saab", "जी": "ji", "हाँ": "haan", "हां": "haan", "ना": "na", "नाम": "naam",
    "बात": "baat", "वाला": "wala", "वाले": "wale", "वाली": "wali", "दवा": "dawa", "दवाई": "dawai",
    "सवाल": "sawal", "जवाब": "jawab", "वक्त": "waqt", "वापस": "wapas", "हवा": "hawa", "वजह": "wajah",
    "ज़रूर": "zaroor", "जरूर": "zaroor", "पैसे": "paise", "पैसा": "paisa",
    "रुपये": "rupaye", "रुपए": "rupaye", "रूपे": "rupaye", "रुपे": "rupaye",
    "महीने": "mahine", "महीना": "mahina", "हफ्ते": "hafte", "हफ़्ते": "hafte", "दिन": "din", "साल": "saal",
    "फ़ायदा": "fayda", "फायदा": "fayda", "मदद": "madad", "मतलब": "matlab", "बिल्कुल": "bilkul",
    "सही": "sahi", "गलत": "galat", "पहले": "pehle", "बाद": "baad", "फिर": "phir", "अगर": "agar",
    "लेकिन": "lekin", "इसलिए": "isliye", "जैसे": "jaise", "वैसे": "waise", "जैसा": "jaisa",
    "मेरा": "mera", "मेरे": "mere", "मेरी": "meri", "मुझे": "mujhe", "उनसे": "unse", "उनको": "unko",
    "किया": "kiya", "करना": "karna", "करके": "karke", "करें": "karein", "कीजिए": "kijiye",
    "बताइए": "bataiye", "बताइये": "bataiye", "दीजिए": "dijiye", "लीजिए": "lijiye",
    "हुआ": "hua", "हुई": "hui", "हुए": "hue", "होगा": "hoga", "होगी": "hogi", "होंगे": "honge",
    "ज्यादा": "zyada", "ज़्यादा": "zyada", "जादा": "zyada", "ज़ादा": "zyada", "कम": "kam",
    "थोड़ा": "thoda", "थोड़ी": "thodi", "जोड़ों": "jodon", "जोड़": "jod", "दर्द": "dard", "पेट": "pet",
    "सुबह": "subah", "शाम": "shaam", "पानी": "paani", "खाना": "khana", "खाने": "khane",
    "गर्म": "garam", "गरम": "garam", "डब्बे": "dabbe", "डब्बा": "dabba", "प्रतिशत": "pratishat",
    "हकीम": "hakim", "हाकीम": "hakim", "यूनानी": "unani", "नुस्खा": "nuskha", "नुस्खे": "nuskhe",
    "शुक्रिया": "shukriya", "धन्यवाद": "dhanyavaad", "नमस्ते": "namaste",
    # --- English words that Whisper writes in Devanagari -----------------------
    "हेलो": "hello", "हैलो": "hello", "हलो": "hello", "ओके": "ok", "थैंक्यू": "thank you",
    "कॉल": "call", "काल": "call", "मॉक": "mock", "टीम": "team", "एक्सपर्ट": "expert", "हेड": "head",
    "कैप्सूल": "capsule", "कैपसूल": "capsule", "कैप्सुल": "capsule", "कैप्सूल्स": "capsules",
    "टैबलेट": "tablet", "टेबलेट": "tablet", "टीवी": "TV", "टी.वी.": "TV", "शो": "show",
    "डिस्काउंट": "discount", "डिसकाउंट": "discount", "परसेंट": "percent", "परसैंट": "percent",
    "पर्सेंट": "percent", "रिलीफ": "relief", "रिलीफ़": "relief", "चेंजेस": "changes", "चेंज": "change",
    "हेल्थ": "health", "ऑर्डर": "order", "आर्डर": "order", "आडर": "order",
    "डिलीवरी": "delivery", "डिलिवरी": "delivery", "पेमेंट": "payment", "नंबर": "number",
    "ऑनलाइन": "online", "ऑफलाइन": "offline", "प्रॉब्लम": "problem", "प्रोब्लम": "problem",
    "प्रॉब्लेम": "problem", "कैटेगरी": "category", "कैटगरी": "category", "पेशेंट": "patient",
    "पेशेंट्स": "patients", "कंसल्टेशन": "consultation", "स्टार्ट": "start", "ट्रेंड": "trained",
    "ट्रेनिंग": "training", "फ़ोन": "phone", "फोन": "phone", "मोबाइल": "mobile", "मैसेज": "message",
    "व्हाट्सएप": "WhatsApp", "कोर्स": "course", "बुक": "book", "बुकिंग": "booking",
    "कन्फर्म": "confirm", "कंफर्म": "confirm", "एड्रेस": "address", "पिन": "pin", "कोड": "code",
    "रेडी": "ready", "टेस्ट": "test", "रिकॉर्डिंग": "recording", "रेकॉर्डिंग": "recording",
    "रिकॉर्ड": "record", "प्रोडक्ट": "product", "पैकेट": "packet", "पैक": "pack", "बॉक्स": "box",
    "डोज": "dose", "डोज़": "dose", "रिजल्ट": "result", "रिपोर्ट": "report", "डॉक्टर": "doctor",
    "क्लिनिक": "clinic", "कंपनी": "company", "ऑफिस": "office", "सर": "sir", "मैडम": "madam",
    "प्लीज": "please", "प्लीज़": "please", "रिसीव": "receive", "कनेक्ट": "connect",
    "डिस्कनेक्ट": "disconnect", "सपोर्ट": "support", "पेन": "pain", "स्ट्रॉन्ग": "strong",
}
